routes/web.php
<?php

use App\Http\Controllers\admin\AdminBlogController;
use App\Http\Controllers\admin\AdminGalleryController;
use App\Http\Controllers\admin\AdminHomeController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\HomepageController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('/')->group(function () {
    Route::resource('/', HomepageController::class);
    Route::resource('blog', BlogController::class);
    Route::resource('gallery', GalleryController::class);
});

Route::middleware(['auth'])->prefix('admin')->as('admin.')->group(function () {
    Route::resource('/', AdminHomeController::class);
    Route::resource('blog', AdminBlogController::class);
    Route::resource('gallery', AdminGalleryController::class);
});

Auth::routes(['register' => false]);

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/blog-view.blade.php
@extends('layouts.master')

@section('title')
    {{$data->title}} -
@endsection

@section('content')
    <!-- hero section starts -->
    <section id="blog" class="dtr-section dtr-section-with-bg dtr-hero-section-top-padding bg-blue"
        style="background-image: url({{ asset('assets/images/white-shape-bg.png') }});">

        <!-- wrapping div for background bottom curve stripes image - easy to change color - no need to edit image - refer help doc -->
        <div class="dtr-bottom-shape-img" style="background-image: url({{ asset('assets/images/hero-bottom.svg') }});">
            <div class="container">

                <!--===== row 1 starts =====-->
                <div class="row">

                    <!-- column 1 starts -->
                    <div class="col-12 text-center">

                        <!-- intro text -->
                        <h1 class="color-white">{{$data->title}}</h1>
                        <br>
                        <br>
                    </div>
                    <!-- column 1 ends -->

                </div>
                <!--===== row 1 ends =====-->

            </div>
        </div>
    </section>
    <!-- hero section ends -->

    <!-- blog section starts -->
    <section id="blog" class="dtr-section dtr-py-100">
        <div class="container">

            <!--== row starts ==-->
            <div class="row dtr-mt-0">

                <!-- column 1 starts -->
                <div class="col-12 mb-5">
                    <img src="{{ asset('media/images/'.$data->image) }}" alt="image" style="width: 100%">
                </div>
                <!-- column 1 ends -->

                <!-- column 2 starts -->
                <div class="col-12">
                    {{date('D, d F Y'), strtotime($data->created_at)}}
                    <br>
                    <br>
                    {!!$data->desc!!}
                    <br>
                    <br>
                    <div class="btn-group" role="group" aria-label="Lampiran">
                        <a href="{{ asset('media/archives/'.$data->archive) }}" class="btn btn-primary" download="{{$data->title}}">
                            <i class="icon-download"></i>
                        </a>
                        <a href="{{ asset('media/archives/'.$data->archive) }}" target="_blank" class="btn btn-blue">Lihat Lampiran</a>
                    </div>

                </div>
                <!-- column 2 ends -->

            </div>
            <!--== row starts ==-->

        </div>
    </section>
    <!-- blog section ends -->
@endsection

resources/views/blog.blade.php
@extends('layouts.master')

@section('title', 'Publikasi - ')

@section('content')
    <!-- hero section starts -->
    <section id="publikasi" class="dtr-section dtr-section-with-bg dtr-hero-section-top-padding bg-blue"
        style="background-image: url({{ asset('assets/images/white-shape-bg.png') }});">

        <!-- wrapping div for background bottom curve stripes image - easy to change color - no need to edit image - refer help doc -->
        <div class="dtr-bottom-shape-img" style="background-image: url({{ asset('assets/images/hero-bottom.svg') }});">
            <div class="container">

                <!--===== row 1 starts =====-->
                <div class="row">

                    <!-- column 1 starts -->
                    <div class="col-12 text-center">

                        <!-- intro text -->
                        <h1 class="color-white">Publikasi</h1>
                        <br>
                        <br>

                    </div>
                    <!-- column 1 ends -->

                </div>
                <!--===== row 1 ends =====-->

            </div>
        </div>
    </section>
    <!-- hero section ends -->

    <!-- blog section starts -->
    <section id="publikasi" class="dtr-section dtr-py-100">
        <div class="container">

            <!-- heading starts -->
            <div class="dtr-styled-heading text-center">
                <h2>Recent Articles</h2>
            </div>
            <!-- heading ends -->

            <!--== row starts ==-->
            <div class="row dtr-mt-0">

                <!-- column 1 starts -->
                @foreach ($data as $item)
                <div class="col-12 col-md-4">

                    <!-- blog item 1 starts -->
                    <div class="dtr-blog-item">
                        <!-- image -->
                        <a href="{{ route('blog.show', $item->slug) }}">
                            <div class="dtr-post-img"> <img src="{{ asset('media/images/'.$item->image) }}"
                                    alt="image">
                                <span class="dtr-blog-date">{{date('d M'), strtotime($item->created_at)}} <br>
                                    {{date('Y'), strtotime($item->created_at)}}</span>
                            </div>
                            <!-- content -->
                            <h5>{{$item->title}}</h5>
                        </a>
                        {{-- <p class="text-truncate">{!!$item->desc!!}</p> --}}
                    </div>
                    <!-- blog item 1 ends -->

                </div>
                @endforeach
                <!-- column 1 ends -->

            </div>
            <!--== row starts ==-->

        </div>
    </section>
    <!-- blog section ends -->
@endsection

resources/views/gallery.blade.php
@extends('layouts.master')

@section('title', 'Gallery - ')

@section('content')
    <!-- hero section starts -->
    <section id="publikasi" class="dtr-section dtr-section-with-bg dtr-hero-section-top-padding bg-blue"
        style="background-image: url({{ asset('assets/images/white-shape-bg.png') }});">

        <!-- wrapping div for background bottom curve stripes image - easy to change color - no need to edit image - refer help doc -->
        <div class="dtr-bottom-shape-img" style="background-image: url({{ asset('assets/images/hero-bottom.svg') }});">
            <div class="container">

                <!--===== row 1 starts =====-->
                <div class="row">

                    <!-- column 1 starts -->
                    <div class="col-12 text-center">

                        <!-- intro text -->
                        <h1 class="color-white">Gallery</h1>
                        <br>
                        <br>

                    </div>
                    <!-- column 1 ends -->

                </div>
                <!--===== row 1 ends =====-->

            </div>
        </div>
    </section>
    <!-- hero section ends -->

    <!-- blog section starts -->
    <section id="publikasi" class="dtr-section dtr-py-100">
        <div class="container">

            <!--== row starts ==-->
            <div class="row dtr-mt-0">

                <!-- column 1 starts -->
                @foreach ($data as $item)
                    <div class="col-12 col-md-3">

                        <!-- blog item 1 starts -->
                        <div class="dtr-blog-item">
                            <!-- image -->
                            {{-- <a href=""> --}}
                            <button type="button" class="btn" data-toggle="modal"
                                data-target="#galleryModal{{ $item->id }}">
                                <div class="polaroid">
                                    <img src="{{ asset('media/images/' . $item->image) }}" alt="{{ $item->title }}"
                                        class="img-fluid">
                                    <div class="container">
                                        <p>{{ $item->title }}</p>
                                    </div>
                                </div>
                            </button>
                            {{-- </a> --}}
                        </div>
                        <!-- blog item 1 ends -->

                    </div>
                @endforeach
                <!-- column 1 ends -->

            </div>
            <!--== row starts ==-->

        </div>
    </section>
    <!-- blog section ends -->

    <!-- Modal -->
    @foreach ($data as $item)
        <div class="modal fade" id="galleryModal{{ $item->id }}" tabindex="-1" role="dialog"
            aria-labelledby="galleryModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="galleryModalLabel">{{ $item->title }}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <img src="{{ asset('media/images/' . $item->image) }}" alt="{{ $item->title }}"
                            class="img-fluid">
                    </div>
                </div>
            </div>
        </div>
    @endforeach
@endsection

@section('css')
    <style>
        div.polaroid {
            width: 250px;
            height: 100%;
            background-color: white;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            margin-bottom: 25px;
        }

        div.container {
            text-align: center;
            padding: 10px 20px;
        }

        button:focus {
            outline: 0;
        }

    </style>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection