routes/web.php
<?php

use App\Http\Controllers\admin\AdminBlogController;
use App\Http\Controllers\admin\AdminGalleryController;
use App\Http\Controllers\admin\AdminHomeController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\HomepageController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('/')->group(function () {
    Route::resource('/', HomepageController::class);
    Route::resource('blog', BlogController::class);
    Route::resource('gallery', GalleryController::class);
});

Route::middleware(['auth'])->prefix('admin')->as('admin.')->group(function () {
    Route::resource('/', AdminHomeController::class);
    Route::resource('blog', AdminBlogController::class);
    Route::resource('gallery', AdminGalleryController::class);
});

Auth::routes(['register' => false]);

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Gallery.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Gallery extends Model
{
    use HasFactory;

    protected $table = 'gallery';

    protected $fillable = [
        'title',
        'image',
    ];
}

app/Http/Controllers/GalleryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Gallery;
use Illuminate\Http\Request;

class GalleryController extends Controller
{
    public function index()
    {
        $data = Gallery::all();
        return view('gallery', compact('data'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        //
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        //
    }

    public function destroy($id)
    {
        //
    }
}

resources/views/admin/gallery/create.blade.php
@extends('layouts.admin.master')

@section('title', 'New Image - ')

@section('title-bar', 'New Image')

@section('breadcrumb')
    <a href="#" class="breadcrumb-item"><i class="far fa-newspaper m-r-5"></i>Image</a>
    <a href="{{ route('admin.gallery.index') }}" class="breadcrumb-item">Index</a>
    <span class="breadcrumb-item active">New Image</span>
@endsection

@section('content')
    <form action="{{ route('admin.gallery.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="form-group row">
            <label for="title" class="col-sm-2 col-form-label">Title</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="title" name="title" placeholder="title" required>
            </div>
        </div>
        <div class="form-group row">
            <label for="image" class="col-sm-2 col-form-label">Image</label>
            <div class="col-sm-9 ml-3 custom-file">
                <input type="file" name="image" class="custom-file-input" id="customFile" required>
                <label class="custom-file-label" for="customFile">Choose file</label>
            </div>
        </div>
        <div class="form-group row d-flex justify-content-end">
            <div class="col-sm-10">
                <a href="{{ url()->previous() }}" class="btn btn-secondary btn-tone">Back</a>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
@endsection

@section('js')
    <script>
        $(".custom-file-input").on("change", function() {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
@endsection

resources/views/admin/gallery/edit.blade.php
@extends('layouts.admin.master')

@section('title')
    {{$data->title}} -
@endsection

@section('title-bar', 'Edit Image')

@section('breadcrumb')
    <a href="#" class="breadcrumb-item"><i class="far fa-newspaper m-r-5"></i>Image</a>
    <a href="{{ route('admin.gallery.index') }}" class="breadcrumb-item">Index</a>
    <span class="breadcrumb-item active">{{$data->title}}</span>
@endsection

@section('content')
    <form action="{{ route('admin.gallery.update', $data->id) }}" method="POST" enctype="multipart/form-data">
        @method('PUT')
        @csrf
        <div class="form-group row">
            <label for="title" class="col-sm-2 col-form-label">Title</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="title" value="{{$data->title}}" name="title" placeholder="title" required>
            </div>
        </div>
        <div class="form-group row">
            <label for="image" class="col-sm-2 col-form-label">Image</label>
            <div class="col-sm-9 ml-3 custom-file">
                <input type="file" name="image" class="custom-file-input" id="customFile">
                <label class="custom-file-label" for="customFile">{{$data->image}}</label>
            </div>
        </div>
        <div class="form-group row d-flex justify-content-end">
            <div class="col-sm-10">
                <a href="{{ url()->previous() }}" class="btn btn-secondary btn-tone">Back</a>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
@endsection

@section('js')
    <script>
        $(".custom-file-input").on("change", function() {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
@endsection

resources/views/admin/gallery/index.blade.php
@extends('layouts.admin.master')

@section('title', 'Gallery -')

@section('title-bar', 'Gallery')

@section('breadcrumb')
    <a href="#" class="breadcrumb-item"><i class="fas fa-images m-r-5"></i>Gallery</a>
    <span class="breadcrumb-item active">Index</span>
@endsection

@section('content')
    <div class="card">
        <div class="card-body">
            <div class="d-flex justify-content-between">
                <h4>Gallery</h4>
                <a href="{{ route('admin.gallery.create') }}" class="btn btn-primary btn-rounded" id="trigger-loading-1">
                    <i class="fas fa-plus-circle"></i> New Gallery
                    <i class="anticon anticon-loading"></i>
                </a>
            </div>
            <div class="m-t-25">
                <table id="data-table" class="table">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Date</th>
                            <th>Title</th>
                            <th>Image</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($data as $key => $item)
                            <tr>
                                <td>{{ $key + 1 }}</td>
                                <td>{{ date('d M Y'), strtotime($item->created_at) }}</td>
                                <td>{{ $item->title }}</td>
                                <td>
                                    <img src="{{ asset('media/images/' . $item->image) }}" alt="" style="width: 100px">
                                </td>
                                <td>
                                    <div class="d-flex justify-content-start align-items-center">
                                        {{-- <a href="{{ route('admin.gallery.show', $item->id) }}" title="Show"
                                            class="btn btn-sm ml-3 btn-info"><i class="fas fa-eye"></i></a> --}}
                                        <button type="button" class="btn btn-sm btn-info" data-toggle="modal"
                                            data-target="#galleryModal{{$item->id}}">
                                            <i class="fas fa-eye"></i>
                                        </button>
                                        <a href="{{ route('admin.gallery.edit', $item->id) }}"
                                            class="btn btn-sm ml-3 btn-secondary" title="Edit"><i
                                                class="fas fa-pencil-alt"></i></a>
                                        <form onsubmit="return confirm('Are you sure to delete {{ $item->title }}?')"
                                            action="{{ route('admin.gallery.destroy', $item->id) }}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-sm ml-3 btn-danger" title="Delete"><i
                                                    class="fas fa-trash"></i></button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>No</th>
                            <th>Date</th>
                            <th>Title</th>
                            <th>Image</th>
                            <th>Action</th>
                        </tr>
                    </tfoot>
                </table>
                <!-- Modal -->
                @foreach ($data as $item)
                    <div class="modal fade" id="galleryModal{{$item->id}}" tabindex="-1" role="dialog"
                        aria-labelledby="galleryModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="galleryModalLabel">{{ $item->title }}</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <img src="{{ asset('media/images/' . $item->image) }}" alt="{{ $item->title }}" class="img-fluid">
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
@endsection

@section('css')
    <link href="{{ asset('assets/admin/vendors/datatables/dataTables.bootstrap.min.css') }}" rel="stylesheet">
@endsection

@section('js')
    <script src="{{ asset('assets/admin/vendors/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('assets/admin/vendors/datatables/dataTables.bootstrap.min.js') }}"></script>

    <script>
        $('#data-table').DataTable();
    </script>
    <script>
        $('#trigger-loading-1').on('click', function(e) {
            $(this).addClass("is-loading");
            setTimeout(function() {
                $("#trigger-loading-1").removeClass("is-loading");
            }, 4000);
            // e.preventDefault();
        });
    </script>
@endsection