routes/web.php
<?php

use App\Http\Controllers\admin\AdminBlogController;
use App\Http\Controllers\admin\AdminGalleryController;
use App\Http\Controllers\admin\AdminHomeController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\HomepageController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('/')->group(function () {
    Route::resource('/', HomepageController::class);
    Route::resource('blog', BlogController::class);
    Route::resource('gallery', GalleryController::class);
});

Route::middleware(['auth'])->prefix('admin')->as('admin.')->group(function () {
    Route::resource('/', AdminHomeController::class);
    Route::resource('blog', AdminBlogController::class);
    Route::resource('gallery', AdminGalleryController::class);
});

Auth::routes(['register' => false]);

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    use HasFactory;

    protected $table = 'blog';

    protected $fillable = [
        'title',
        'slug',
        'desc',
        'image',
        'archive'
    ];
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Blog;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    public function index()
    {
        $data = Blog::all();
        return view('blog', compact('data'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        //
    }

    public function show($slug)
    {
        $data = Blog::where('slug', $slug)->first();
        return view('blog-view', compact('data'));
    }

    public function edit($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        //
    }

    public function destroy($id)
    {
        //
    }
}

resources/views/admin/blog/create.blade.php
@extends('layouts.admin.master')

@section('title', 'New Article - ')

@section('title-bar', 'New Article')

@section('breadcrumb')
    <a href="#" class="breadcrumb-item"><i class="far fa-newspaper m-r-5"></i>Article</a>
    <a href="{{ route('admin.blog.index') }}" class="breadcrumb-item">Index</a>
    <span class="breadcrumb-item active">New Article</span>
@endsection

@section('content')
    <form action="{{ route('admin.blog.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="form-group row">
            <label for="title" class="col-sm-2 col-form-label">Title</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="title" name="title" placeholder="title" required>
            </div>
        </div>
        <div class="form-group row">
            <label for="desc" class="col-sm-2 col-form-label">Desc</label>
            <div class="col-sm-10">
                <textarea id="mytextarea" name="desc"></textarea>
            </div>
        </div>
        <div class="form-group row">
            <label for="image" class="col-sm-2 col-form-label">Image</label>
            <div class="col-sm-9 ml-3 custom-file">
                <input type="file" name="image" class="custom-file-input" id="customFile" required>
                <label class="custom-file-label" for="customFile">Choose file</label>
            </div>
        </div>
        <div class="form-group row">
            <label for="archive" class="col-sm-2 col-form-label">Archive</label>
            <div class="col-sm-9 ml-3 custom-file">
                <input type="file" name="archive" class="custom-file-input" id="customFile">
                <label class="custom-file-label" for="customFile">Choose file</label>
            </div>
        </div>
        <div class="form-group row d-flex justify-content-end">
            <div class="col-sm-10">
                <a href="{{ url()->previous() }}" class="btn btn-secondary btn-tone">Back</a>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
@endsection

@section('js')
    <script>
        $(".custom-file-input").on("change", function() {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
    <script src="{{ asset('assets/admin/js/tinymce/tinymce.min.js') }}"></script>
    <script type="text/javascript">
        tinymce.init({
            selector: '#mytextarea'
        });
    </script>
@endsection

resources/views/admin/blog/edit.blade.php
@extends('layouts.admin.master')

@section('title')
    {{ $data->title }} -
@endsection

@section('title-bar', 'Article')

@section('breadcrumb')
    <a href="#" class="breadcrumb-item"><i class="far fa-newspaper m-r-5"></i>Article</a>
    <a href="{{ route('admin.blog.index') }}" class="breadcrumb-item">Index</a>
    <span class="breadcrumb-item active">{{ $data->title }}</span>
@endsection

@section('content')
    <form action="{{ route('admin.blog.update', $data->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="form-group row">
            <label for="title" class="col-sm-2 col-form-label">Title</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="title" name="title" value="{{ $data->title }}"
                    placeholder="title" required>
            </div>
        </div>
        <div class="form-group row">
            <label for="desc" class="col-sm-2 col-form-label">Desc</label>
            <div class="col-sm-10">
                <textarea id="mytextarea" name="desc">{{ $data->desc }}</textarea>
            </div>
        </div>
        <div class="form-group row">
            <label for="image" class="col-sm-2 col-form-label">Image</label>
            <div class="col-sm-9 ml-3 custom-file">
                <input type="file" name="image" value="{{ $data->image }}" class="custom-file-input" id="customFile">
                <label class="custom-file-label" for="customFile">{{ $data->image }}</label>
            </div>
        </div>
        <div class="form-group row">
            <label for="archive" class="col-sm-2 col-form-label">Archive</label>
            <div class="col-sm-9 ml-3 custom-file">
                <input type="file" name="archive" value="{{ $data->archive }}" class="custom-file-input" id="customFile">
                <label class="custom-file-label" for="customFile">
                    {{ $data->archive != null ? $data->archive : '-' }}
                </label>
            </div>
        </div>
        <div class="form-group row d-flex justify-content-end">
            <div class="col-sm-10">
                <a href="{{ url()->previous() }}" class="btn btn-secondary btn-tone">Back</a>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
@endsection

@section('js')
    <script>
        $(".custom-file-input").on("change", function() {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
    <script src="{{ asset('assets/admin/js/tinymce/tinymce.min.js') }}"></script>
    <script type="text/javascript">
        tinymce.init({
            selector: '#mytextarea'
        });
    </script>
@endsection

resources/views/admin/blog/index.blade.php
@extends('layouts.admin.master')

@section('title', 'Article - ')

@section('title-bar', 'Article')

@section('breadcrumb')
    <a href="#" class="breadcrumb-item"><i class="far fa-newspaper m-r-5"></i>Article</a>
    <span class="breadcrumb-item active">Index</span>
@endsection

@section('content')
    <div class="card">
        <div class="card-body">
            <div class="d-flex justify-content-between">
                <h4>Article</h4>
                <a href="{{ route('admin.blog.create') }}" class="btn btn-primary btn-rounded" id="trigger-loading-1">
                    <i class="fas fa-plus-circle"></i> New Article
                    <i class="anticon anticon-loading"></i>
                </a>
            </div>
            <div class="m-t-25">
                <table id="data-table" class="table">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Date</th>
                            <th>Title</th>
                            <th>Image</th>
                            <th>Archive</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($data as $key => $item)
                            <tr>
                                <td>{{ $key + 1 }}</td>
                                <td>{{ date('d M Y'), strtotime($item->created_at) }}</td>
                                <td>{{ $item->title }}</td>
                                <td>
                                    <img src="{{ asset('media/images/' . $item->image) }}" alt="" style="width: 100px">
                                </td>
                                <td>
                                    @if ($item->archive == true)
                                        <a href="{{ asset('media/archives/' . $item->archive) }}" target="_blank"
                                            class="btn btn-sm btn-info">
                                            Lihat Lampiran
                                        </a>
                                    @else
                                        -
                                    @endif
                                </td>
                                <td>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <a href="{{ route('admin.blog.show', $item->id) }}" title="Show"
                                            class="btn btn-sm btn-info"><i class="fas fa-eye"></i></a>
                                        <a href="{{ route('admin.blog.edit', $item->id) }}"
                                            class="btn btn-sm btn-secondary" title="Edit"><i
                                                class="fas fa-pencil-alt"></i></a>
                                        <form onsubmit="return confirm('Are you sure to delete {{ $item->title }}?')"
                                            action="{{ route('admin.blog.destroy', $item->id) }}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-sm btn-danger" title="Delete"><i
                                                    class="fas fa-trash"></i></button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>No</th>
                            <th>Date</th>
                            <th>Title</th>
                            <th>Image</th>
                            <th>Archive</th>
                            <th>Action</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
@endsection

@section('css')
    <link href="{{ asset('assets/admin/vendors/datatables/dataTables.bootstrap.min.css') }}" rel="stylesheet">
@endsection

@section('js')
    <script src="{{ asset('assets/admin/vendors/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('assets/admin/vendors/datatables/dataTables.bootstrap.min.js') }}"></script>

    <script>
        $('#data-table').DataTable();
    </script>
    <script>
        $('#trigger-loading-1').on('click', function(e) {
            $(this).addClass("is-loading");
            setTimeout(function() {
                $("#trigger-loading-1").removeClass("is-loading");
            }, 4000);
            // e.preventDefault();
        });
    </script>
@endsection

resources/views/admin/blog/show.blade.php
@extends('layouts.admin.master')

@section('title')
    {{ $data->title }} -
@endsection

@section('title-bar', 'Article')

@section('breadcrumb')
    <a href="#" class="breadcrumb-item"><i class="far fa-newspaper m-r-5"></i>Article</a>
    <a href="{{ route('admin.blog.index') }}" class="breadcrumb-item">Index</a>
    <span class="breadcrumb-item active">{{ $data->title }}</span>
@endsection

@section('content')
    {{-- <form method="POST" enctype="multipart/form-data">
        @csrf
        <div class="form-group row">
            <label for="title" class="col-sm-2 col-form-label">Title</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="title" name="title" value="{{ $data->title }}"
                    placeholder="title" required>
            </div>
        </div>
        <div class="form-group row">
            <label for="desc" class="col-sm-2 col-form-label">Desc</label>
            <div class="col-sm-10">
                <textarea id="mytextarea" name="desc">{{ $data->desc }}</textarea>
            </div>
        </div>
        <div class="form-group row">
            <label for="image" class="col-sm-2 col-form-label">Image</label>
            <div class="col-sm-9 ml-3 custom-file">
                <input type="file" name="image" value="{{ $data->image }}" class="custom-file-input" id="customFile"
                    required>
                <label class="custom-file-label" for="customFile">{{ $data->image }}</label>
            </div>
        </div>
        <div class="form-group row">
            <label for="archive" class="col-sm-2 col-form-label">Archive</label>
            <div class="col-sm-9 ml-3 custom-file">
                <input type="file" name="archive" value="{{ $data->archive }}" class="custom-file-input" id="customFile"
                    required>
                <label class="custom-file-label" for="customFile">
                    {{ $data->archive != null ? $data->archive : '-' }}
                </label>
            </div>
        </div>
    </form> --}}
    <div class="card">
        <div class="card-body">
            <div class="container">
                <h2 class="font-weight-normal m-b-10">{{$data->title}}</h2>
                <div class="d-flex m-b-10">
                    <p class="m-b-0 text-muted font-size-13">{{date('M d, Y'), strtotime($data->created_at)}}</p>
                </div>
                <img alt="" class="img-fluid w-100" src="{{asset('media/images/'.$data->image)}}">
                <div class="m-t-10">
                    {!! $data->desc !!}
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script>
        $(".custom-file-input").on("change", function() {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
    <script src="{{ asset('assets/admin/js/tinymce/tinymce.min.js') }}"></script>
    <script type="text/javascript">
        tinymce.init({
            selector: '#mytextarea'
        });
    </script>
@endsection